[#] update pipework for cgroup2

diff --git a/pipework b/pipework
--- a/pipework
+++ b/pipework
@@ -1,11 +1,15 @@
 #!/bin/sh
 # This code should (try to) follow Google's Shell Style Guide
-# (https://google-styleguide.googlecode.com/svn/trunk/shell.xml)
+# (https://google.github.io/styleguide/shell.xml)
 set -e
 
 case "$1" in
   --wait)
     WAIT=1
+    ;;
+  --direct-phys)
+    DIRECT_PHYS=1
+    shift
     ;;
 esac
 
@@ -15,6 +19,18 @@ IFNAME=$1
 CONTAINER_IFNAME=
 if [ "$2" = "-i" ]; then
   CONTAINER_IFNAME=$3
+  shift 2
+fi
+
+if [ "$2" = "-l" ]; then
+  LOCAL_IFNAME=$3
+  shift 2
+fi
+
+#inet or inet6
+FAMILY_FLAG="-4"
+if [ "$2" = "-a" ]; then
+  FAMILY_FLAG="-$3"
   shift 2
 fi
 
@@ -33,10 +49,26 @@ case "$MACADDR" in
     ;;
 esac
 
+# did they ask to generate a custom MACADDR?
+# generate the unique string
+case "$MACADDR" in
+  U:*)
+    macunique="${MACADDR#*:}"
+    # now generate a 48-bit hash string from $macunique
+    MACADDR=$(echo $macunique|md5sum|sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\).*$/02:\1:\2:\3:\4:\5/')
+   ;;
+esac
+
+
 [ "$IPADDR" ] || [ "$WAIT" ] || {
   echo "Syntax:"
-  echo "pipework <hostinterface> [-i containerinterface] <guest> <ipaddr>/<subnet>[@default_gateway] [macaddr][@vlan]"
-  echo "pipework <hostinterface> [-i containerinterface] <guest> dhcp [macaddr][@vlan]"
+  echo "pipework <hostinterface> [-i containerinterface] [-l localinterfacename] [-a addressfamily] <guest> <ipaddr>/<subnet>[@default_gateway] [macaddr][@vlan]"
+  echo "pipework <hostinterface> [-i containerinterface] [-l localinterfacename] <guest> dhcp [macaddr][@vlan]"
+  echo "pipework mac:<hostinterface_macaddress> [-i containerinterface] [-l localinterfacename] [-a addressfamily] <guest> <ipaddr>/<subnet>[@default_gateway] [macaddr][@vlan]"
+  echo "pipework mac:<hostinterface_macaddress> [-i containerinterface] [-l localinterfacename] <guest> dhcp [macaddr][@vlan]"
+  echo "pipework route <guest> <route_command>"
+  echo "pipework rule <guest> <rule_command>"
+  echo "pipework tc <guest> <tc_command>"
   echo "pipework --wait [-i containerinterface]"
   exit 1
 }
@@ -60,25 +92,26 @@ die () {
   exit "$status"
 }
 
-wait_for_container(){
-  dockername=$@
-  while true
-  do
-    status=`docker inspect $dockername | grep Running | awk -F ':' '{print $2}' | tr -d " :,"`
-    if [ $status = "true" ]
-    then
+if echo $IFNAME | grep -q '^mac:'; then
+  mac_address=$(echo $IFNAME | cut -c5-)
+  ifmatch=
+  for iftest in /sys/class/net/*; do
+    if [ -f $iftest/address ] && [ "$mac_address" = "$(cat $iftest/address)" ]; then
+      ifmatch="$(basename $iftest)"
       break
-    else
-      sleep 1      
     fi
   done
-}
 
-wait_for_container $GUESTNAME
+  if [ -z "$ifmatch" ]; then
+    die 1 "Mac address $mac_address specified for interface but no host interface matched."
+  else
+    IFNAME=$ifmatch
+  fi
+fi
 
 # First step: determine type of first argument (bridge, physical interface...),
 # Unless "--wait" is set (then skip the whole section)
-if [ -z "$WAIT" ]; then 
+if [ -z "$WAIT" ]; then
   if [ -d "/sys/class/net/$IFNAME" ]
   then
     if [ -d "/sys/class/net/$IFNAME/bridge" ]; then
@@ -87,10 +120,11 @@ if [ -z "$WAIT" ]; then
     elif installed ovs-vsctl && ovs-vsctl list-br|grep -q "^${IFNAME}$"; then
       IFTYPE=bridge
       BRTYPE=openvswitch
-    elif [ "$(cat "/sys/class/net/$IFNAME/type")" -eq 32 ]; then # Infiniband IPoIB interface type 32
+    elif [ "$(cat "/sys/class/net/$IFNAME/type")" -eq 32 ]; then # InfiniBand IPoIB interface type 32
       IFTYPE=ipoib
       # The IPoIB kernel module is fussy, set device name to ib0 if not overridden
       CONTAINER_IFNAME=${CONTAINER_IFNAME:-ib0}
+      PKEY=$VLAN
     else IFTYPE=phys
     fi
   else
@@ -105,6 +139,18 @@ if [ -z "$WAIT" ]; then
         fi
         IFTYPE=bridge
         BRTYPE=openvswitch
+        ;;
+      route*)
+        IFTYPE=route
+        ;;
+      rule*)
+        IFTYPE=rule
+        ;;
+      tc*)
+        IFTYPE=tc
+        ;;
+      dummy*)
+        IFTYPE=dummy
         ;;
       *) die 1 "I do not know how to setup interface $IFNAME." ;;
     esac
@@ -134,19 +180,27 @@ CONTAINER_IFNAME=${CONTAINER_IFNAME:-eth1}
   die 1 "MACADDR configuration unsupported for IPoIB interfaces."
 }
 
-# Second step: find the guest (for now, we only support LXC containers)
-while read _ mnt fstype options _; do
-  [ "$fstype" != "cgroup" ] && continue
-  echo "$options" | grep -qw devices || continue
-  CGROUPMNT=$mnt
-done < /proc/mounts
+if grep cgroup2 /proc/filesystems > /dev/null ; then 
+  N=0
+else
+  # Second step: find the guest (for now, we only support LXC containers)
+  while read _ mnt fstype options _; do
+    [ "$fstype" != "cgroup" ] && continue
+    echo "$options" | grep -qw devices || continue
+    CGROUPMNT=$mnt
+  done < /proc/mounts
 
-[ "$CGROUPMNT" ] || {
+  [ "$CGROUPMNT" ] || {
     die 1 "Could not locate cgroup mount point."
-}
+  }
 
-# Try to find a cgroup matching exactly the provided name.
-N=$(find "$CGROUPMNT" -name "$GUESTNAME" | wc -l)
+  # Try to find a cgroup matching exactly the provided name.
+  M=$(find "$CGROUPMNT" -name "$GUESTNAME")
+  N=$(echo "$M" | wc -l)
+  if [ -z "$M" ] ; then
+    N=0
+  fi
+fi
 case "$N" in
   0)
     # If we didn't find anything, try to lookup the container with Docker.
@@ -154,6 +208,9 @@ case "$N" in
       RETRIES=3
       while [ "$RETRIES" -gt 0 ]; do
         DOCKERPID=$(docker inspect --format='{{ .State.Pid }}' "$GUESTNAME")
+        DOCKERCID=$(docker inspect --format='{{ .ID }}' "$GUESTNAME")
+        DOCKERCNAME=$(docker inspect --format='{{ .Name }}' "$GUESTNAME")
+
         [ "$DOCKERPID" != 0 ] && break
         sleep 1
         RETRIES=$((RETRIES - 1))
@@ -171,39 +228,59 @@ case "$N" in
     fi
     ;;
   1) true ;;
+  2)  # LXC >=3.1.0 returns two entries from the cgroups mount instead of one.
+      echo "$M" | grep -q "lxc\.monitor" || die 1 "Found more than one container matching $GUESTNAME."
+      ;;
   *) die 1 "Found more than one container matching $GUESTNAME." ;;
 esac
 
-if [ "$IPADDR" = "dhcp" ]; then
-  # Check for first available dhcp client
-  DHCP_CLIENT_LIST="udhcpc dhcpcd dhclient"
-  for CLIENT in $DHCP_CLIENT_LIST; do
-    installed "$CLIENT" && {
-      DHCP_CLIENT=$CLIENT
-      break
-    }
-  done
-  [ -z "$DHCP_CLIENT" ] && {
-    die 1 "You asked for DHCP; but no DHCP client could be found."
-  }
-else
-  # Check if a subnet mask was provided.
+# only check IPADDR if we are not in a route mode
+[ "$IFTYPE" != route ] && [ "$IFTYPE" != rule ] && [ "$IFTYPE" != tc ] && {
   case "$IPADDR" in
-    */*) : ;;
-    *)
-      warn "The IP address should include a netmask."
-      die 1 "Maybe you meant $IPADDR/24 ?"
-      ;;
+	  # Let's check first if the user asked for DHCP allocation.
+	  dhcp|dhcp:*)
+	    # Use Docker-specific strategy to run the DHCP client
+	    # from the busybox image, in the network namespace of
+	    # the container.
+	    if ! [ "$DOCKERPID" ]; then
+	      warn "You asked for a Docker-specific DHCP method."
+	      warn "However, $GUESTNAME doesn't seem to be a Docker container."
+	      warn "Try to replace 'dhcp' with another option?"
+	      die 1 "Aborting."
+	    fi
+	    DHCP_CLIENT=${IPADDR%%:*}
+	    ;;
+	  udhcpc|udhcpc:*|udhcpc-f|udhcpc-f:*|dhcpcd|dhcpcd:*|dhclient|dhclient:*|dhclient-f|dhclient-f:*)
+	    DHCP_CLIENT=${IPADDR%%:*}
+	    # did they ask for the client to remain?
+	    DHCP_FOREGROUND=
+	    [ "${DHCP_CLIENT%-f}" != "${DHCP_CLIENT}" ] && {
+	      DHCP_FOREGROUND=true
+	    }
+	    DHCP_CLIENT=${DHCP_CLIENT%-f}
+	    if ! installed "$DHCP_CLIENT"; then
+	      die 1 "You asked for DHCP client $DHCP_CLIENT, but I can't find it."
+	    fi
+	    ;;
+	  # Alright, no DHCP? Then let's see if we have a subnet *and* gateway.
+	  */*@*)
+	    GATEWAY="${IPADDR#*@}" GATEWAY="${GATEWAY%%@*}"
+	    IPADDR="${IPADDR%%@*}"
+	    ;;
+	  # No gateway? We need at least a subnet, anyway!
+	  */*) : ;;
+	  # ... No? Then stop right here.
+	  *)
+	    warn "The IP address should include a netmask."
+	    die 1 "Maybe you meant $IPADDR/24 ?"
+	    ;;
   esac
-  # Check if a gateway address was provided.
+}
+
+# If a DHCP method was specified, extract the DHCP options.
+if [ "$DHCP_CLIENT" ]; then
   case "$IPADDR" in
-    *@*)
-      GATEWAY="${IPADDR#*@}" GATEWAY="${GATEWAY%%@*}"
-      IPADDR="${IPADDR%%@*}"
-      ;;
-    *)
-      GATEWAY=
-      ;;
+    *:*) DHCP_OPTIONS="${IPADDR#*:}" ;;
   esac
 fi
 
@@ -212,7 +289,11 @@ if [ "$DOCKERPID" ]; then
 else
   NSPID=$(head -n 1 "$(find "$CGROUPMNT" -name "$GUESTNAME" | head -n 1)/tasks")
   [ "$NSPID" ] || {
-    die 1 "Could not find a process inside container $GUESTNAME."
+    # it is an alternative way to get the pid
+    NSPID=$(lxc-info -n  "$GUESTNAME" | grep PID | grep -Eo '[0-9]+')
+    [ "$NSPID" ] || {
+      die 1 "Could not find a process inside container $GUESTNAME."
+    }
   }
 fi
 
@@ -238,30 +319,43 @@ ln -s "/proc/$NSPID/ns/net" "/var/run/netns/$NSPID"
   }
 }
 
-MTU=$(ip link show "$IFNAME" | awk '{print $5}')
+[ "$IFTYPE" != "route" ] && [ "$IFTYPE" != "dummy" ] && [ "$IFTYPE" != "rule" ] && [ "$IFTYPE" != "tc" ] && MTU=$(ip link show "$IFNAME" | awk '{print $5}')
+
 # If it's a bridge, we need to create a veth pair
 [ "$IFTYPE" = bridge ] && {
-  LOCAL_IFNAME="v${CONTAINER_IFNAME}pl${NSPID}"
+  if [ -z "$LOCAL_IFNAME" ]; then
+    LOCAL_IFNAME="v${CONTAINER_IFNAME}pl${NSPID}"
+  fi
   GUEST_IFNAME="v${CONTAINER_IFNAME}pg${NSPID}"
+  # Does the link already exist?
+  if ip link show "$LOCAL_IFNAME" >/dev/null 2>&1; then
+    # link exists, is it in use?
+    if ip link show "$LOCAL_IFNAME" up | grep -q "UP"; then
+      echo "Link $LOCAL_IFNAME exists and is up"
+      exit 1
+    fi
+    # delete the link so we can re-add it afterwards
+    ip link del "$LOCAL_IFNAME"
+  fi
   ip link add name "$LOCAL_IFNAME" mtu "$MTU" type veth peer name "$GUEST_IFNAME" mtu "$MTU"
   case "$BRTYPE" in
     linux)
       (ip link set "$LOCAL_IFNAME" master "$IFNAME" > /dev/null 2>&1) || (brctl addif "$IFNAME" "$LOCAL_IFNAME")
       ;;
     openvswitch)
-      ovs-vsctl add-port "$IFNAME" "$LOCAL_IFNAME" ${VLAN:+tag="$VLAN"}
+      if ! ovs-vsctl list-ports "$IFNAME" | grep -q "^${LOCAL_IFNAME}$"; then
+        ovs-vsctl add-port "$IFNAME" "$LOCAL_IFNAME" ${VLAN:+tag="$VLAN"} \
+            -- set Interface "$LOCAL_IFNAME" \
+                external-ids:pipework.interface="$LOCAL_IFNAME" \
+                external-ids:pipework.bridge="$IFNAME" \
+                ${DOCKERCID:+external-ids:pipework.containerid="$DOCKERCID"} \
+                ${DOCKERCNAME:+external-ids:pipework.containername="$DOCKERCNAME"} \
+                ${NSPID:+external-ids:pipework.nspid="$NSPID"} \
+                ${VLAN:+external-ids:pipework.vlan="$VLAN"}
+      fi
       ;;
   esac
   ip link set "$LOCAL_IFNAME" up
-}
-
-# Note: if no container interface name was specified, pipework will default to ib0
-# Note: no macvlan subinterface or ethernet bridge can be created against an 
-# ipoib interface. Infiniband is not ethernet. ipoib is an IP layer for it.
-# To provide additional ipoib interfaces to containers use SR-IOV and pipework 
-# to assign them.
-[ "$IFTYPE" = ipoib ] && {
-  GUEST_IFNAME=$CONTAINER_IFNAME
 }
 
 # If it's a physical interface, create a macvlan subinterface
@@ -273,45 +367,132 @@ MTU=$(ip link show "$IFNAME" | awk '{print $5}')
     ip link set "$IFNAME" up
     IFNAME=$IFNAME.$VLAN
   }
-  GUEST_IFNAME=ph$NSPID$CONTAINER_IFNAME
-  ip link add link "$IFNAME" dev "$GUEST_IFNAME" mtu "$MTU" type macvlan mode bridge
+
+  if [ ! -z "$DIRECT_PHYS" ]; then
+    GUEST_IFNAME=$IFNAME
+  else
+    GUEST_IFNAME=ph$NSPID$CONTAINER_IFNAME
+    GUEST_IFNAME=$(echo $GUEST_IFNAME | cut -c 1-15)
+    ip link add link "$IFNAME" dev "$GUEST_IFNAME" mtu "$MTU" type macvlan mode bridge
+  fi
+
   ip link set "$IFNAME" up
 }
 
-ip link set "$GUEST_IFNAME" netns "$NSPID"
-ip netns exec "$NSPID" ip link set "$GUEST_IFNAME" name "$CONTAINER_IFNAME"
-[ "$MACADDR" ] && ip netns exec "$NSPID" ip link set dev "$CONTAINER_IFNAME" address "$MACADDR"
-if [ "$IPADDR" = "dhcp" ]
-then
-  [ "$DHCP_CLIENT" = "udhcpc"  ] && ip netns exec "$NSPID" "$DHCP_CLIENT" -qi "$CONTAINER_IFNAME" -x "hostname:$GUESTNAME"
-  if [ "$DHCP_CLIENT" = "dhclient"  ]; then
-    # kill dhclient after get ip address to prevent device be used after container close
-    ip netns exec "$NSPID" "$DHCP_CLIENT" -pf "/var/run/dhclient.$NSPID.pid" "$CONTAINER_IFNAME"
-    kill "$(cat "/var/run/dhclient.$NSPID.pid")"
-    rm "/var/run/dhclient.$NSPID.pid"
+# If it's an IPoIB interface, create a virtual IPoIB interface (the IPoIB
+# equivalent of a macvlan device)
+#
+# Note: no macvlan subinterface nor Ethernet bridge can be created on top of an
+# IPoIB interface. InfiniBand is not Ethernet. IPoIB is an IP layer on top of
+# InfiniBand, without an intermediate Ethernet layer.
+[ "$IFTYPE" = ipoib ] && {
+  GUEST_IFNAME="${IFNAME}.${NSPID}"
+
+  # If a partition key is provided, use it
+  [ "$PKEY" ] && {
+    GUEST_IFNAME="${IFNAME}.${PKEY}.${NSPID}"
+    PKEY="pkey 0x$PKEY"
+  }
+
+  ip link add link "$IFNAME" name "$GUEST_IFNAME" type ipoib $PKEY
+  ip link set "$IFNAME" up
+}
+
+# If its a dummy interface, create a dummy interface.
+[ "$IFTYPE" = dummy ] && {
+  GUEST_IFNAME=du$NSPID$CONTAINER_IFNAME
+  ip link add dev "$GUEST_IFNAME" type dummy
+}
+
+# If the `route` command was specified ...
+if [ "$IFTYPE" = route ]; then
+  # ... discard the first two arguments and pass the rest to the route command.
+  shift 2
+  ip netns exec "$NSPID" ip route "$@"
+elif [ "$IFTYPE" = rule ] ; then
+  shift 2
+  ip netns exec "$NSPID" ip rule "$@"
+elif [ "$IFTYPE" = tc ] ; then
+  shift 2
+  ip netns exec "$NSPID" tc "$@"
+else
+  # Otherwise, run normally.
+  if command -v iw > /dev/null && iw dev | awk '$1=="Interface"{print $2}' | grep $GUEST_IFNAME > /dev/null; then
+    iw phy $(iw dev | grep -B 1 $GUEST_IFNAME | grep phy# | sed 's/#//g') set netns $NSPID
+  else
+    ip link set "$GUEST_IFNAME" netns "$NSPID"
   fi
-  [ "$DHCP_CLIENT" = "dhcpcd"  ] && ip netns exec "$NSPID" "$DHCP_CLIENT" -q "$CONTAINER_IFNAME" -h "$GUESTNAME"
-else
-  ip netns exec "$NSPID" ip addr add "$IPADDR" dev "$CONTAINER_IFNAME"
-  [ "$GATEWAY" ] && {
-    ip netns exec "$NSPID" ip route delete default >/dev/null 2>&1 && true
-  }
-  ip netns exec "$NSPID" ip link set "$CONTAINER_IFNAME" up
-  [ "$GATEWAY" ] && {
-    ip netns exec "$NSPID" ip route get "$GATEWAY" >/dev/null 2>&1 || \
-    ip netns exec "$NSPID" ip route add "$GATEWAY/32" dev "$CONTAINER_IFNAME"
-    ip netns exec "$NSPID" ip route replace default via "$GATEWAY"
-  }
-fi
+  ip netns exec "$NSPID" ip link set "$GUEST_IFNAME" name "$CONTAINER_IFNAME"
+  [ "$MACADDR" ] && ip netns exec "$NSPID" ip link set dev "$CONTAINER_IFNAME" address "$MACADDR"
 
-# Give our ARP neighbors a nudge about the new interface
-if installed arping; then
-  IPADDR=$(echo "$IPADDR" | cut -d/ -f1)
-  ip netns exec "$NSPID" arping -c 1 -A -I "$CONTAINER_IFNAME" "$IPADDR" > /dev/null 2>&1 || true
-else
-  echo "Warning: arping not found; interface may not be immediately reachable"
-fi
+	# When using any of the DHCP methods, we start a DHCP client in the
+	# network namespace of the container. With the 'dhcp' method, the
+	# client used is taken from the Docker busybox image (therefore
+	# requiring no specific client installed on the host). Other methods
+	# use a locally installed client.
+	case "$DHCP_CLIENT" in
+	  dhcp)
+	    docker run -d --net container:$GUESTNAME --cap-add NET_ADMIN \
+	           busybox udhcpc -i "$CONTAINER_IFNAME" -x "hostname:$GUESTNAME" \
+	           $DHCP_OPTIONS \
+	           >/dev/null
+	    ;;
+	  udhcpc)
+	    DHCP_Q="-q"
+	    [ "$DHCP_FOREGROUND" ] && {
+	      DHCP_OPTIONS="$DHCP_OPTIONS -f"
+	    }
+	    ip netns exec "$NSPID" "$DHCP_CLIENT" -qi "$CONTAINER_IFNAME" \
+	                                          -x "hostname:$GUESTNAME" \
+	                                          -p "/var/run/udhcpc.$GUESTNAME.pid" \
+	                                          $DHCP_OPTIONS
+	    [ ! "$DHCP_FOREGROUND" ] && {
+	      rm "/var/run/udhcpc.$GUESTNAME.pid"
+	    }
+	    ;;
+	  dhclient)
+	    ip netns exec "$NSPID" "$DHCP_CLIENT" "$CONTAINER_IFNAME" \
+	                                          -pf "/var/run/dhclient.$GUESTNAME.pid" \
+	                                          -lf "/etc/dhclient/dhclient.$GUESTNAME.leases" \
+	                                          $DHCP_OPTIONS
+	    # kill dhclient after get ip address to prevent device be used after container close
+	    [ ! "$DHCP_FOREGROUND" ] && {
+	      kill "$(cat "/var/run/dhclient.$GUESTNAME.pid")"
+	      rm "/var/run/dhclient.$GUESTNAME.pid"
+	    }
+	    ;;
+	  dhcpcd)
+	    ip netns exec "$NSPID" "$DHCP_CLIENT" -q "$CONTAINER_IFNAME" -h "$GUESTNAME"
+	    ;;
+	  "")
+	    # Note: expected busybox ipcalc! CK
+	    if installed busybox; then
+	      eval $(busybox ipcalc -b $IPADDR)
+	      ip netns exec "$NSPID" ip "$FAMILY_FLAG" addr add "$IPADDR" brd "$BROADCAST" dev "$CONTAINER_IFNAME"
+	    else
+	      ip netns exec "$NSPID" ip "$FAMILY_FLAG" addr add "$IPADDR" dev "$CONTAINER_IFNAME"
+	    fi
 
+	    [ "$GATEWAY" ] && {
+	      ip netns exec "$NSPID" ip "$FAMILY_FLAG" route delete default >/dev/null 2>&1 && true
+	    }
+	    ip netns exec "$NSPID" ip "$FAMILY_FLAG" link set "$CONTAINER_IFNAME" up
+	    [ "$GATEWAY" ] && {
+	      ip netns exec "$NSPID" ip "$FAMILY_FLAG" route get "$GATEWAY" >/dev/null 2>&1 || \
+	      ip netns exec "$NSPID" ip "$FAMILY_FLAG" route add "$GATEWAY/32" dev "$CONTAINER_IFNAME"
+	      ip netns exec "$NSPID" ip "$FAMILY_FLAG" route replace default via "$GATEWAY" dev "$CONTAINER_IFNAME"
+	    }
+	    ;;
+	esac
+
+  # Give our ARP neighbors a nudge about the new interface
+  if installed arping; then
+    IPADDR=$(echo "$IPADDR" | cut -d/ -f1)
+    ip netns exec "$NSPID" arping -c 1 -A -I "$CONTAINER_IFNAME" "$IPADDR" > /dev/null 2>&1 || true
+  else
+    echo "Warning: arping not found; interface may not be immediately reachable"
+  fi
+fi
 # Remove NSPID to avoid `ip netns` catch it.
 rm -f "/var/run/netns/$NSPID"
 
